markdown: kramdown
theme: minima

collections:
  members:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: default
